#!/bin/sh

VERSION_SNPEFF=3.2
SUBVERSION_SNPEFF=""
VERSION_SNPSIFT=1.8
VERSION_SNPSQL=0.2

ENSEMBL_RELEASE=70

# Version values using underscores ('3_2' instead of '3.2')
SNPEFF_VERSION=`echo $VERSION_SNPEFF | tr "." "_"`
SNPSIFT_VERSION=`echo $VERSION_SNPSIFT | tr "." "_"`
SNPSQL_VERSION=`echo $VERSION_SNPSQL | tr "." "_"`

SNPEFF_VERSION_REV=$SNPEFF_VERSION"$SUBVERSION_SNPEFF"
